# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'model_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13model_service.proto\x12\rmodel_service\x1a\x1bgoogle/protobuf/empty.proto\"f\n\x11TrainModelRequest\x12\x12\n\nmodel_type\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x13\n\x0bparams_json\x18\x03 \x01(\t\x12\x14\n\x0c\x66ile_content\x18\x04 \x01(\x0c\"%\n\x12TrainModelResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"?\n\x13RetrainModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x14\n\x0c\x66ile_content\x18\x02 \x01(\x0c\"\'\n\x14RetrainModelResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\":\n\x0ePredictRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x14\n\x0c\x66ile_content\x18\x02 \x01(\x0c\"&\n\x0fPredictResponse\x12\x13\n\x0bpredictions\x18\x01 \x03(\x02\"(\n\x12\x44\x65leteModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"&\n\x13\x44\x65leteModelResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"C\n\x12ModelTypesResponse\x12-\n\x0bmodel_types\x18\x01 \x03(\x0b\x32\x18.model_service.ModelType\"\x19\n\tModelType\x12\x0c\n\x04name\x18\x01 \x01(\t2\xe5\x03\n\x0cModelService\x12Q\n\nTrainModel\x12 .model_service.TrainModelRequest\x1a!.model_service.TrainModelResponse\x12W\n\x0cRetrainModel\x12\".model_service.RetrainModelRequest\x1a#.model_service.RetrainModelResponse\x12H\n\x07Predict\x12\x1d.model_service.PredictRequest\x1a\x1e.model_service.PredictResponse\x12T\n\x0b\x44\x65leteModel\x12!.model_service.DeleteModelRequest\x1a\".model_service.DeleteModelResponse\x12J\n\rGetModelTypes\x12\x16.google.protobuf.Empty\x1a!.model_service.ModelTypesResponse\x12=\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAINMODELREQUEST']._serialized_start=67
  _globals['_TRAINMODELREQUEST']._serialized_end=169
  _globals['_TRAINMODELRESPONSE']._serialized_start=171
  _globals['_TRAINMODELRESPONSE']._serialized_end=208
  _globals['_RETRAINMODELREQUEST']._serialized_start=210
  _globals['_RETRAINMODELREQUEST']._serialized_end=273
  _globals['_RETRAINMODELRESPONSE']._serialized_start=275
  _globals['_RETRAINMODELRESPONSE']._serialized_end=314
  _globals['_PREDICTREQUEST']._serialized_start=316
  _globals['_PREDICTREQUEST']._serialized_end=374
  _globals['_PREDICTRESPONSE']._serialized_start=376
  _globals['_PREDICTRESPONSE']._serialized_end=414
  _globals['_DELETEMODELREQUEST']._serialized_start=416
  _globals['_DELETEMODELREQUEST']._serialized_end=456
  _globals['_DELETEMODELRESPONSE']._serialized_start=458
  _globals['_DELETEMODELRESPONSE']._serialized_end=496
  _globals['_MODELTYPESRESPONSE']._serialized_start=498
  _globals['_MODELTYPESRESPONSE']._serialized_end=565
  _globals['_MODELTYPE']._serialized_start=567
  _globals['_MODELTYPE']._serialized_end=592
  _globals['_MODELSERVICE']._serialized_start=595
  _globals['_MODELSERVICE']._serialized_end=1080
# @@protoc_insertion_point(module_scope)
